Repository nightscout/trio-docs, pull requests merged in 2025-05, with the labels that each got.

#113 Fix typo, `cgm` ==> `CGM`
  docs/configuration/settings/algorithm/additionals.md
  docs/configuration/settings/devices/cgm.md
  docs/install/build/requirements/devices/cgm.md
  docs/usage/interface.md
Labels: typo

#117 ⚰️ Remove "Build Select Script" page
  docs/install/build/mac/build-select-script.md
  mkdocs.yml
Labels: config

#115 ⚰️ Remove the `docs/Analyze` folder (no longer used)
  docs/Analyze/EvaluateBasal.md
  docs/Analyze/EvaluateCR.md
  docs/Analyze/img/adjustBasal.png
Labels: config

#112 Update remote control
  docs/configuration/settings/features/img/lf-data-source-dexcom.svg
  docs/configuration/settings/features/img/lf-data-source-ns.svg
  docs/configuration/settings/features/img/lf-remote-options.svg
  docs/configuration/settings/features/img/lf-settings-screen.png
  docs/configuration/settings/features/img/lf-settings.svg
  docs/configuration/settings/features/img/lf-table-overview.png
  docs/configuration/settings/features/img/lf-trc-debug-blurred.png
  docs/configuration/settings/features/img/lf-trc-empty-control-settings.jpg
  docs/configuration/settings/features/img/lf-trc-filled-control-settings.png
  docs/configuration/settings/features/img/lf-trc-guardrails.jpg
  docs/configuration/settings/features/img/lf-trc-scheduled-meal.png
  docs/configuration/settings/features/img/lf-trc-selection.jpg
  docs/configuration/settings/features/img/lf-trc.jpg
  docs/configuration/settings/features/img/trio-enable-remote-control.png
  docs/configuration/settings/features/remote-control.md
Labels: documentation

#108 ✏️ Fix the FAQs page
  docs/configuration/CompatibleDevices.md
  docs/help/faq.md
  docs/includes/supported-cgms.md
  docs/install/build/requirements/devices/cgm.md
Labels: typo

#120 Match settings to latest trio version
  docs/configuration/new-user-setup.md
  docs/configuration/settings/algorithm/autosens.md
  docs/configuration/settings/algorithm/smb-settings.md
  docs/configuration/settings/closed-loop.md
  docs/index.md
  mkdocs.yml
Labels: documentation, config, typo

#123 ✏️ Fix Nightscout URL in 0.2.x Docs
  docs/0.2.x/settings/services/nightscout.md
Labels: typo

#125 TrioDocs Domain Migration to `triodocs.org` from `diy‑trio.org`
  docs/CNAME
Labels: config

#126 TrioDocs Domain Migration to `triodocs.org` from `diy‑trio.org` - Part 2
  README.md
  docs/0.2.x/Getting-Started/Overview.md
  docs/0.2.x/resources/translate.md
  docs/0.2.x/settings/configuration/preferences/smbsettings.md
  docs/assets/templates/covers/front.html.j2
  docs/configuration/settings/algorithm/smb-settings.md
  docs/help/translate.md
  mkdocs.yml
Labels: enhancement, config, typo

#133 ♻️ Add a `Build` section above `Build with Mac` and `Build with Browser`
  mkdocs.yml
Labels: enhancement, config

#127 ✏️ Fix TOC, PDF, broken links, unused files
  docs/configuration/new-user-setup.md
  docs/configuration/settings/features/.keepme
  docs/configuration/settings/features/remote-control.md
  mkdocs.yml
Labels: config, typo

#131 ♻️ Reorder TOC Configuration/Trio Settings/Therapy
  docs/configuration/settings/therapy/index.md
  mkdocs.yml
Labels: typo

#144 Fix broken video display in Bolus Calculator page
  docs/assets/stylesheets/extra.css
  docs/usage/features/bolus-calculator.md
Labels: bug, documentation, enhancement, config

#132 📝 Add `App Diagnostics` page
  docs/configuration/settings/features/app-diagnostics.md
  docs/configuration/settings/features/img/trio-app-diagnostics.png
  mkdocs.yml
Labels: documentation

#154 Implement slugified anchors for content tabs based on their names
  docs/configuration/new-user-setup.md
  mkdocs.yml
Labels: enhancement, config

#157 Improve instructions for creating a dev branch for a Trio fork
  docs/install/build/browser/img/choose-trio-app-group.png
  docs/install/build/browser/img/trio-branch.png
  docs/install/build/browser/img/trio-disable-do-not-run.png
  docs/install/build/browser/img/trio-new-branch.png
  docs/install/build/browser/update-with-browser.md
Labels: documentation, enhancement

#160 ❇️ 💄 Add a Lightbox (zoom) effect to images
  docs/0.2.x/index.md
  docs/configuration/index.md
  docs/configuration/migration/index.md
  docs/configuration/settings/algorithm/index.md
  docs/configuration/settings/devices/index.md
  docs/configuration/settings/features/index.md
  docs/configuration/settings/index.md
  docs/configuration/settings/notifications/index.md
  docs/configuration/settings/services/index.md
  docs/configuration/settings/therapy/index.md
  docs/help/index.md
  docs/index.md
  docs/install/ecosystem/index.md
  docs/install/index.md
  docs/usage/index.md
  mkdocs.yml
  requirements.in
  requirements.txt
Labels: enhancement, config, dependencies
